version: '3'
services:
  tunnel:
    image: localtunnel
    container_name: tunnel
    build:
      context: .
      dockerfile: Dockerfile.localtunnel
    entrypoint: lt --port 2023 --subdomain 'rdaq'
    restart: unless-stopped
    network_mode: host
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./proxy/data:/data
      - ./proxy/cert/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  ui:
    image: remotedaq_ui
    container_name: remotedaq_ui
    build: .
    restart: always
    ports:
      - 2023:2023
    volumes:
      - ./main.py:/rdaq-server/main.py:ro
      - ./.env:/rdaq-server/.env:ro
      - ./.env-node:/rdaq-server/.env-node
      - ./logs:/rdaq-server/logs
  data_db:
    image: influxdb:alpine
    container_name: remotedaq_db
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-config:/etc/influxdb2
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-config:
    external: True
  influxdb-data:
    external: True