version: '3'
services:
  data_db:
    image: influxdb
    container_name: data_db
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data:
    external: True