version: '3'
services:
  ui:
    image: remotedaq_app
    container_name: remotedaq_app
    build: .
    restart: always
    ports:
      - 2023
    volumes:
      - ./main.py:main.py:ro
  data_db:
    image: influxdb
    container_name: data_db
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data:
    external: True