version: '3'
services:
  ui:
    image: remotedaq_ui
    container_name: remotedaq_ui
    build: .
    restart: always
    ports:
      - 2023:2023
    volumes:
      - ./main.py:/rdaq-server/main.py:ro
      - ./.env:/rdaq-server/.env:ro
      - ./.env-node:/rdaq-server/.env-node
      - ./ssh-creds:/rdaq-server/ssh-creds:ro
  data_db:
    image: influxdb:alpine
    container_name: remotedaq_db
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-config:/etc/influxdb2
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-config:
    external: True
  influxdb-data:
    external: True