version: '3'
services:
  ui:
    image: remotedaq_ui
    container_name: remotedaq_ui
    build: .
    restart: always
    ports:
      - 2023:2023
    volumes:
      - ./main.py:/main.py:ro
  data_db:
    image: influxdb:alpine
    container_name: remotedaq_db
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data:
    external: True