version: '3'
services:
  ui:
    image: remotedaq_ui
    container_name: remotedaq_ui
    build: .
    restart: always
    environment:
      - ZT_ID=${ZT_ID}
    ports:
      - 2023:2023
    volumes:
      - ./main.py:/rdaq-server/main.py:ro
      - ./settings.json:/rdaq-server/settings.json
  data_db:
    image: influxdb:alpine
    container_name: remotedaq_db
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data:
    external: True